### ISSUE TITLE
Email gets stuck in Processfolder

### ISSUE THREAD

**Issue by perhornesjo** [KofaxRPA/RPA-11.1#3]
If an email arrives at the same time as an ongoing process running longer than 10 minutes. Then the email will get stuck in the Process folder.
The email gets stuck in the folder and will not continue to be processed even if services or server are restarted.
It will also not be processed if the email is moved to the inbox.

How can I get RPA to continue processing this email?
Where is information about the email stored?

**Comment by TungstenRPA** [comment]
Hi Per,

You are talking here about a product issue that should be reported to Technical Support at https://support.kofax.com.

David

**Comment by perhornesjo** [comment]
Okey, I report it.
Thanks
